### PR TITLE
Islandora 2251

### PR DESCRIPTION
**Pull request by DonRichards**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2251

https://docs.google.com/spreadsheets/d/1PtK16Fo2q4jTMgz17DYmV1nauvoGDEi6f2fhl9K1ZIA

# What does this Pull Request do?

Makes the XPaths editable through an admin GUI

ISLANDORA SCHOLAR XPATH CONFIGURATION

# What's new?

Islandora Scholar XPath Configuration Section located on the /admin/islandora/solution_pack_config/scholar page. It allows you to modify the previously hard coded XPaths and reset them at any time. 

# How should this be tested?
* Start islandora_vagrant and ingest an item (prior to switching to this PR)
  * Inspect it and test that the search results look like expects
  * from the terminal
```terminal
      $ vagrant ssh
      $ cd /var/ww/drupal
      $ drush vget islandora_scholar_default_search_xpath
      No matching variable found.
```
* Switch to this PR
  * Go to /admin/islandora/solution_pack_config/scholar page and click 'Save Configuration'
  * from the terminal
```terminal
      $ vagrant ssh
      $ cd /var/ww/drupal
      $ drush vget islandora_scholar_default_search_xpath
...
```
  * This time you should see several results
  * Ingest an item
  * Try modifying an XPath (easiest is to switch title with something else)
  * Check that the change shows up on a new ingest and an existing one. 
  * Also try adding new values to the citation_form.xml or thesis_form.xml and see if pointing to the new values works. 

# Additional Notes:

* This change requires documentation to be updated.
* This should not impact existing installations.
* This does **NOT** modify the submission form.
* This allows for the 52 XPaths and 3 subpaths to be set
* This exclude subpaths in a few spots where they occurred.
    * Check google doc for excluded some paths

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by bryjbrown** [comment]
@DonRichards Thanks for making a PR for this! This is going to be a complicated thing to pull off and I have a lot of opinions on it, but unfortunately I'm swamped this week and out on vacation next week. I'll try to find some time to run a test when I can and give some feedback, but it may be a bit.

**Comment by DonRichards** [comment]
@bryjbrown No problem. Although there is a lot to review, it's easy/quick to test. It also defaults to not changing anything and falls back on the current configuration until something is saved (and even then it still applies the current defaults unless otherwise set). I tried to keep it simple. Not a lot new.

**Comment by DonRichards** [comment]
This is what switching the title and abstract would look like.

**Comment by DonRichards** [comment]
@bryjbrown How should we initialize the discussion for this? Group meeting or just Q/A on here?

**Comment by DonRichards** [comment]
I'm having some issues with this PR branch ever sense the outage yesterday. It dropped the association with the repo branch. 

download

**Comment by DiegoPino** [comment]
@DonRichards you will have to close this pull and reopen, pretty sure that can not be edited by us. Once the original repository you used to make the pull does not longer exists, it lives in limbo. Maybe some other @Islandora/7-x-1-x-committers knows a trick 2 two to fix that?  Probably you could try recreating the deleted repository on your side and force push the branch where this one originated and cross fingers github becomes aware of the change and then magically reconnects this..

**Comment by DonRichards** [comment]
Thanks @DiegoPino! Will do it now.

**Pull request closed without merging**
