### PR TITLE
Clearing up hook naming changes.

### PR DESCRIPTION
**Pull request by knjackson30974**
**Jira:** https://jira.duraspace.org/browse/ISLANDORA-1637
# What does this Pull Request do?

Addresses hook naming changes in xml_form_builder. 
# How should this be tested?

Check that hook names match hook names in xml_form_builder.api.php
# Background context:
# Additional Notes:
- **Does this change require documentation to be updated?** No.
- **Does this change add any new dependencies?** No.
- **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
- **Could this change impact execution of existing code?** If any implementations of the hooks were missed perhaps. Would be minor. 

**Tagging:** Will tag on islandora_xml_forms to keep things less redundant. 

---

Kylea Jackson

_Developer_

**[discoverygarden inc.](http://www.discoverygarden.ca) | Managing Digital Content**

### CODE REVIEW

**Comment by whikloj** [comment]
This PR depends on https://github.com/Islandora/islandora_xml_forms/pull/221

**Comment by bryjbrown** [comment]
@DiegoPino Since https://github.com/Islandora/islandora_xml_forms/pull/221 has been merged, what are the next steps for this PR?

**Comment by DiegoPino** [comment]
@bryjbrown i'm testing all of them now (13). Will have this one merged in 15 minutes if all goes right.

**Review by DiegoPino — APPROVED** [review]
Part of a 13 piece set. Tested and works with XML forms [#221](https://github.com/Islandora/islandora_xml_forms/pull/221) pull merged. Merging now! @bryjbrown 👀

**Comment by bryjbrown** [comment]
Great work @DiegoPino!

**Pull request merged**
