### PR TITLE
ISLANDORA-2398: Adds subtitle to citation_title metatag

### PR DESCRIPTION
**Pull request by bryjbrown**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2398

# What does this Pull Request do?
Formats citation_title to include MODS subTitle element if available.

# How should this be tested?
Find or create two repository objects, one with no subtitle and one with a subtitle. Check the HTML of both to see that, with the current code, the citation_title metatag is only displaying the MODS title content. Switch to this PR and see that the element with no subtitle stayed the same, but the object with the subtitle now outputs it in the citation_title metatag.

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by bondjimbond** [comment]
@bryjbrown What happens if the configured XPath is dc.title, which already includes the subtitle?

**Comment by bryjbrown** [comment]
@bondjimbond I thought these configurable XPaths could only target MODS datastreams? Is that not the case? Pinging @DonRichards

**Comment by bondjimbond** [comment]
Good question! I'm not actually sure; MODS-only does make sense though.

**Comment by bryjbrown** [comment]
paging @dannylamb, after merging https://github.com/Islandora/islandora_scholar/pull/316 I'm not sure how to pull in the freshest islandora/islandora_scholar 7.x branch into my bryjbrown/islandora_scholar ISLANDORA-2398 so that this PR will have the new .travis.yml file?

**Comment by bryjbrown** [comment]
Nvm, figured it out. #remotecontrol

**Comment by bryjbrown** [comment]
@Islandora/7-x-1-x-committers Alrighty, now this PR passes thanks to @bondjimbond. Anybody else want to review? @DonRichards?

**Comment by bryjbrown** [comment]
@Islandora/7-x-1-x-committers Still looking for a review on this. A Google rep reached out to us personally to tell us this was a problem that hurts indexing, so I'd like to get this merged in ASAP so we can get back to them.

@DonRichards You know more about the way the XPath configs work than anyone else at this point, any thoughts on this?

**Review by jonathangreen — APPROVED** [review]
Looks good to me. Starting ⏱.

**Comment by jonathangreen** [comment]
Don't want to step on your toes @DonRichards, if you have feedback on this one, but change looks good to me, and does what is says in my test site.

**Pull request merged**
