### PR TITLE
7.x documentation

### PR DESCRIPTION
**Pull request by rosiel**
Documentation for 7.x-1.11
Sister pr: #294.

# What does this Pull Request do?

Improves READMEs.

# How should this be tested?

Read the readmes: 

# Additional Notes:

I took out the "Romeo-centric" screenshot of the main config screen because it's only one of several config screens, because it doesn't explain what the module does, and because of the predominance of the SHERPA/ROMEO stuff it misleads as to what the module does. Instead, I direct the user to the Wiki which has also been clarified.

# Interested parties
@DiegoPino  @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@rosiel seems like we have some Travis issue here. Can you give it a look?

**Review by bryjbrown — APPROVED** [review]
Looks good to me! The updates to the DOI configuration menu also reduce some of the cognitive load for users by only showing them options that are appropriate for the given configuration. @rosiel++

**Comment by bryjbrown** [comment]
@DiegoPino 24 to merge, right?

**Comment by rosiel** [comment]
Being documentation, it's at your discretion

**Comment by DiegoPino** [comment]
@bryjbrown actually, since release is today as soon as possible is preferred (not forcing you of course =)

**Comment by rosiel** [comment]
Thanks @bryjbrown!!

**Pull request merged**
