### PR TITLE
Islandora 2338

### PR DESCRIPTION
**Pull request by cdeaneGit**
**JIRA Ticket Islandora/ISLANDORA-2338**: (https://jira.duraspace.org/browse/ISLANDORA-2338)
Update screenshots in README.md and wiki page for RC 7.x-1.12 Islandora_scholar module

* Other Relevant Links 
Click here do download the OVA file for Islandora 7.x-1.12 RC to create the test environment.
https://drive.google.com/file/d/1zPqO4rfiZ5k61HUcYIj4QTtHqMh1fW1y/view

# Purpose
This is meant to keep the README.md file up to date.

# What's new?
REMOVE CURRENT IMAGE
current_xpath_config

INSERT PROPOSED IMAGE
proposed_xpath_config

# How should this be tested?
1.  Bring up Islandora Release Candidate 7.x-1.12 in vagrant using the RC 7.x-1.12 OVA file.

2.  Navigate to HOME >> Administration >> Islandora >> Solution Pack Configuration >> Scholar
    (http://localhost:8000/node#overlay=admin/islandora/solution_pack_config/scholar)
    
3.  Move from the BASIC CONFIGURATION tab to the XPATH CONFIGURATION tab.
    (http://localhost:8000/node#overlay=admin/islandora/solution_pack_config/scholar/xpaths)

4.  Check the box labeled "Enable Custom Paths"

5.  Confirm that the proposed image shown in this pull request matches the content seen under the XPATH CONFIGURATION tab.

If these images match, the test is passed.

# Additional Notes:
This change will require an update to the wiki page 
https://wiki.duraspace.org/display/ISLANDORA/Islandora+Scholar
which is also addressed in  https://jira.duraspace.org/browse/ISLANDORA-2338

This change does not impact existing code in Islandora RC 7.x-1.12.

# Interested parties
@Islandora/7-x-1-x-committers
@Don Richards
@bryjbrown

### CODE REVIEW

**Comment by bryjbrown** [comment]
@cdeaneGit Thanks for handling this! I know its kind of a pain.

The Travis test succeeded on every test except for the last one, which I think may have just been a random timing issue perhaps, since there's no good reason for it to pass elsewhere. I restarted the Travis build and we'll see how that goes.

@cdeaneGit, since this is release time any new PRs require a bit of extra work. Since we now have the 7.x AND 7.x-1.12 branches separately, we need PRs for both. Since you made all of your changes on top of 7.x-1.12, the 7.x-1.12 PR was the easier one to start with, but in order to get these changes into the core 7.x branch that will be used for future releases, we need you to do the following steps:
1. Switch branches in your local copy to 7.x, and do a `git pull` to make sure it is on the latest commit
2. Create a new branch based on 7.x
3. Make the changes that this PR makes (swap the actual image file and the link in the README.md file) in that new branch, commit them and push them up to your GitHub
4. Make a new PR against Scholar's 7.x branch

That sounds like a lot of work, but you've already done the hard part by making the screenshot and everything, this is just a little bit of extra work to make sure we don't lose this change after the release. 

Thanks!

**Comment by bryjbrown** [comment]
Awesome, looks like it WAS just a network issue that caused the failed test, the restarted build passed. This PR is good to go :+1:

**Comment by DonRichards** [comment]
@bryjbrown Are you ok with the screenshots as jpg files located within the repo? I know people have had negative opinions about that in the past.

**Comment by cdeaneGit** [comment]
Hi Don,

This is a png made from the jpg file.  I can push this to my repository at

https://github.com/cdeaneGit/islandora_scholar (ISLANDORA-2338)


cheers!
cricket!

**Comment by bryjbrown** [comment]
@DonRichards I am okay with them being included in the module, but on second look I would strongly prefer that they be moved into the /images directory. @cdeaneGit Apologies for not seeing this the first time, but could you move the images and recommit?

**Comment by DonRichards** [comment]
@bryjbrown just before your post Cricket removed the images and applied the screenshots in a more consistent way.

**Comment by bryjbrown** [comment]
@DonRichards Awesome, that works for me. :+1: to merge.

**Comment by bondjimbond** [comment]
Cool. I see this is going into 7.x-1.12 - have we got a 7.x version for this pull as well?

**Comment by bryjbrown** [comment]
@cdeaneGit Great work, I'm about to merge this PR for 7.x-1.12, so you are absolutely good to go with making these exact changes on the 7.x branch. :+1:

**Comment by cdeaneGit** [comment]
Thanks for all the help.  New pr to go to 7.x on the way.
@bryjbrown 
@DonRichards 
@bondjimbond

**Pull request merged**
