### PR TITLE
Update README.md - fix typo

### PR DESCRIPTION
**Pull request by manez**
# What does this Pull Request do?

Fixes a typo.

# What's new?
_moudle_ becomes _module_.

# How should this be tested?

Review the change. Confirm that 'moudle' is not a thing but 'module' is.

# Interested parties
@bryjbrown or @DonRichards want to give it a go?

### CODE REVIEW

**Review by bryjbrown — APPROVED** [review]
:+1:

**Comment by DonRichards** [comment]
Curious why the other PR failed but this one passed? The Code (except the README) should be identical. Looking at [Travis PR-264 Test](https://travis-ci.org/Islandora/islandora_scholar/builds/223668535)

Was something merged into one but not the other? @bryjbrown @manez

**Comment by DiegoPino** [comment]
Because this has already the Tests Fix pull merged in place that allows running Travis-CI under all PHP versions and PHPUnit ones. https://github.com/Islandora/islandora_scholar/commit/820e7fabd785316ccca77c6093039d8eb400f964

**Comment by DiegoPino** [comment]
Nobody merged this? Ok, will do now. The release one was merged 10 days ago,

**Pull request merged**
