### PR TITLE
Documentation: Update Screenshot for 7.x 1.8

### PR DESCRIPTION
**Pull request by DonRichards**
JIRA Ticket: https://jira.duraspace.org/browse/ISLANDORA-1821

What does this Pull Request do?

Changes screenshot
and adds PR content that was missed on last PR to 1.8

What's new?

Replaces with a more up to date screenshot
Adds names of maintainers

How should this be tested?

Using GUI verify it has the new fields

Additional Notes:

N/A

Interested parties

@dannylamb @manez @bryjbrown @Islandora/7-x-1-x-committers

Screen shot is missing fields. Lots of items need further documentation but will explore in the wiki.

### CODE REVIEW

**Comment by DonRichards** [comment]
Related to https://github.com/Islandora/islandora_scholar/pull/241 for release.

**Comment by DonRichards** [comment]
@ruebot I don't follow you. I start @ 7.x but it appears that the 7.x 1.8 branch was missing the maintainers pull so it included it. I added a comment on the PR about it.

**Comment by rosiel** [comment]
I think the extra commits are all idempotent (not gonna hurt anything). Don, what I think happened is that you maybe pulled the 7.x branch commits about maintainers. These commits had also been put in 7.x-1.8 but they have different commit hashes. 

There's a LOT of git-fu involved in making pull requests during release time (I've screwed things up more often than I've gotten it right!) so I'm going to look at improving the documentation. What I've figured out from a lot of trial and error is that after making a HEAD pull request, i have to change branches to the fresh islandora release branch (git checkout 7.x-1.8) then cherry-pick, not pull, my PR commit from my other branch. I can't just create out a 1.8 branch identical to my head branch because it's likely that the commits diverged at some point.  If you cherry-pick, then the commit may have the same hash. If you don't cherry-pick, and instead you re-do the edits directly to the code (not the greatest idea but I've done it before if it's just a one-liner, or if the context has changed enough that cherry-picking doesn't work) and commit; then the commit will have a different hash. 

I'm ok with merging this despite the extra commits; @DonRichards  @ruebot please let me know if cleanliness is important to you enough to wait for a redo.

**Comment by DonRichards** [comment]
Good point. I'll make a different PR after this merges.

**Comment by dannylamb** [comment]
No worries.  Just gonna squash it anyway.

**Pull request merged**
